---
applications:
- name: sboot-mysql-crud
  instances: 2
  memory: 1G
  disk_quota: 1G
  path: "../target/sboot-mysql-crud.jar"
  #services:
  #  - mysql
  env:
    SPRING_PROFILES_ACTIVE : dev
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}' 
  routes:
    - route: sboot-mysql-crud.cfapps.io
